export {
  IconDevis,
  IconRelance,
  IconPointage,
  IconMarge,
  IconCalendrier,
  IconConformite,
  IconChantier,
  IconTresorerie,
  IconVoix,
  IconPropose,
  IconApprend,
  IconEquipe,
  IconAccueil,
  IconClient,
  IconCatalogue,
  IconReglages,
  IconMenu,
  IconAjouter,
  IconNotification,
  IconRapport,
  IconRecherche,
  type AtelierIconProps,
} from './AtelierIcons'
