// Script de vérification locale des documents pdf-lib.
// Usage : npx tsx scripts/render-pdf-samples.mts
// Écrit les PDF générés dans .scratch/pdf/ (gitignoré) pour inspection visuelle.
//
// Ne dépend pas de Supabase : les données sont des fixtures en dur, et les
// polices sont lues directement depuis le filesystem (pas de fetch réseau),
// contrairement au runtime Workers qui fetch les assets via HTTP.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Organization } from '../src/lib/data/queries/organization'
import type { QuoteWithItems } from '../src/lib/data/queries/quotes'
import type { Client } from '../src/lib/data/queries/clients'
import type { InvoiceWithItems } from '../src/lib/data/queries/invoices'
import { renderQuotePdfWithFonts } from '../src/lib/pdf/documents/quote'
import { renderInvoicePdfWithFonts } from '../src/lib/pdf/documents/invoice'
import type { FontBytes } from '../src/lib/pdf/engine/fonts'

const OUT_DIR = join(process.cwd(), '.scratch', 'pdf')
mkdirSync(OUT_DIR, { recursive: true })

function loadFontsFromDisk(): FontBytes {
  const dir = join(process.cwd(), 'public', 'fonts')
  const read = (name: string) => {
    const buf = readFileSync(join(dir, name))
    return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer
  }
  return {
    interRegular: read('inter-regular.ttf'),
    interBold: read('inter-bold.ttf'),
    headingBold: read('plus-jakarta-sans-bold.ttf'),
    headingXBold: read('plus-jakarta-sans-extrabold.ttf'),
  }
}

const organization: Organization = {
  id: 'org-1',
  name: 'Weber Tôlerie',
  slug: 'weber-tolerie',
  siret: '123 456 789 00012',
  siren: '123456789',
  vat_number: 'FR12345678900',
  email: 'contact@weber-tolerie-demo.fr',
  phone: '01 23 45 67 89',
  address_line1: '12 rue des Artisans',
  address_line2: null,
  city: 'Lyon',
  postal_code: '69000',
  country: 'France',
  logo_url: null,
  email_from_name: 'Weber Tôlerie',
  email_from_address: 'contact@weber-tolerie-demo.fr',
  forme_juridique: 'SARL au capital de',
  capital_social: '10000',
  rcs: '123 456 789',
  rcs_ville: 'Lyon',
  insurance_info: 'AXA France IARD, contrat n° 987654321',
  certifications: 'Qualibat 4321, RGE',
  decennale_enabled: true,
  decennale_assureur: 'AXA France IARD',
  decennale_police: '987654321',
  decennale_couverture: 'Tous corps d\'état',
  decennale_date_debut: '2026-01-01',
  decennale_date_fin: '2026-12-31',
  primary_color: '#FF9F1C',
  payment_terms_days: 30,
  late_penalty_rate: 10,
  court_competent: 'Tribunal de commerce de Lyon',
  iban: 'FR76 1234 5678 9012 3456 7890 123',
  bic: 'BNPAFRPPXXX',
  bank_name: 'BNP Paribas',
  recovery_indemnity_text: null,
  auto_reminder_enabled: true,
  invoice_reminder_days: [7, 14],
  quote_reminder_days: [3, 7],
  reminder_hour_utc: 8,
  sector: 'btp',
  business_profile: null,
  business_activity_id: null,
  secondary_activity_ids: null,
  label_set: null,
  unit_set: null,
  default_categories: null,
  starter_presets: null,
  is_vat_subject: true,
  tva_sur_debits: false,
  default_vat_rate: 20,
  public_form_enabled: false,
  public_form_welcome_message: null,
  public_form_catalog_item_ids: null,
  public_form_custom_mode_enabled: false,
  public_form_notification_email: null,
}

const client: Client = {
  id: 'client-1',
  organization_id: 'org-1',
  type: 'company',
  company_name: 'Dupont Industrie',
  contact_name: 'Jean Dupont',
  first_name: null,
  last_name: null,
  email: 'jean.dupont@dupont-industrie.fr',
  phone: '06 12 34 56 78',
  siret: '987 654 321 00098',
  address_line1: '45 avenue de la République',
  city: 'Villeurbanne',
  postal_code: '69100',
  status: 'active',
  source: null,
  total_revenue: 0,
  payment_terms_days: 30,
  internal_notes: null,
  created_at: '2026-01-01T00:00:00Z',
}

const quote: QuoteWithItems = {
  id: 'quote-1',
  number: 'DEV-2026-001',
  title: 'Fabrication et pose garde-corps',
  status: 'sent',
  total_ht: null,
  total_ttc: null,
  currency: 'EUR',
  validity_days: 30,
  valid_until: null,
  sent_at: '2026-08-01T10:00:00Z',
  signed_at: '2026-08-05T14:30:00Z',
  client_signature_image: null,
  client_signatory_name: 'Jean Dupont',
  client_signatory_role: 'Directeur technique',
  created_at: '2026-08-01T10:00:00Z',
  client: { id: 'client-1', company_name: 'Dupont Industrie', email: 'jean.dupont@dupont-industrie.fr' },
  sections: [
    {
      id: 'section-1',
      quote_id: 'quote-1',
      title: 'Fourniture',
      position: 0,
      items: [
        {
          id: 'item-1',
          quote_id: 'quote-1',
          section_id: 'section-1',
          type: 'material',
          material_id: null,
          labor_rate_id: null,
          designation: 'Garde-corps acier galvanisé',
          details: 'Hauteur 1m\nBarreaudage vertical\nFinition thermolaquée RAL 7016',
          description: null,
          quantity: 12,
          unit: 'ml',
          unit_price: 145.5,
          unit_cost_ht: 90,
          ai_confidence: null,
          ai_source: null,
          ai_warnings: null,
          vat_rate: 20,
          total_ht: null,
          position: 0,
          length_m: 12,
          width_m: null,
          height_m: 1,
          dim_quantity: 1,
          is_internal: false,
          metal_grid_id: null,
          price_pending: false,
          labor_category: null,
        },
        {
          id: 'item-2',
          quote_id: 'quote-1',
          section_id: 'section-1',
          type: 'material',
          material_id: null,
          labor_rate_id: null,
          designation: 'Platines de fixation inox',
          details: null,
          description: null,
          quantity: 8,
          unit: 'u',
          unit_price: 22,
          unit_cost_ht: 14,
          ai_confidence: null,
          ai_source: null,
          ai_warnings: null,
          vat_rate: 20,
          total_ht: null,
          position: 1,
          length_m: null,
          width_m: null,
          height_m: null,
          dim_quantity: 1,
          is_internal: false,
          metal_grid_id: null,
          price_pending: false,
          labor_category: null,
        },
      ],
    },
    {
      id: 'section-2',
      quote_id: 'quote-1',
      title: 'Main d\'œuvre',
      position: 1,
      items: [
        {
          id: 'item-3',
          quote_id: 'quote-1',
          section_id: 'section-2',
          type: 'labor',
          material_id: null,
          labor_rate_id: null,
          designation: 'Pose et installation',
          details: null,
          description: null,
          quantity: 2,
          unit: 'jour',
          unit_price: 380,
          unit_cost_ht: 250,
          ai_confidence: null,
          ai_source: null,
          ai_warnings: null,
          vat_rate: 20,
          total_ht: null,
          position: 0,
          length_m: null,
          width_m: null,
          height_m: null,
          dim_quantity: 1,
          is_internal: false,
          metal_grid_id: null,
          price_pending: false,
          labor_category: 'pose',
        },
        {
          id: 'item-4',
          quote_id: 'quote-1',
          section_id: 'section-2',
          type: 'labor',
          material_id: null,
          labor_rate_id: null,
          designation: 'Étude technique complémentaire',
          details: null,
          description: null,
          quantity: 1,
          unit: 'forfait',
          unit_price: 0,
          unit_cost_ht: null,
          ai_confidence: null,
          ai_source: null,
          ai_warnings: null,
          vat_rate: 20,
          total_ht: null,
          position: 1,
          length_m: null,
          width_m: null,
          height_m: null,
          dim_quantity: 1,
          is_internal: false,
          metal_grid_id: null,
          price_pending: true,
          labor_category: 'autre',
        },
      ],
    },
  ],
  unsectionedItems: [],
  client_request_description: 'Bonjour, nous souhaitons faire poser un garde-corps sécurisé sur notre quai de chargement, environ 12 mètres linéaires.',
  client_request_visible_on_pdf: true,
  notes_client: 'Merci de votre confiance. Ce devis a été établi suite à notre visite technique du 28 juillet.',
  payment_conditions: 'Acompte de 30% à la commande, solde à réception.',
  discount_rate: null,
  deposit_rate: 30,
  aid_label: null,
  aid_amount: null,
  show_section_subtotals: true,
  variant_group_id: null,
  variant_label: null,
  technical_checklist: null,
}

const invoice: InvoiceWithItems = {
  id: 'invoice-1',
  number: 'FAC-2026-042',
  title: 'Fabrication et pose garde-corps',
  status: 'sent',
  invoice_type: 'situation',
  total_ht: null,
  total_tva: null,
  total_ttc: null,
  total_paid: 0,
  currency: 'EUR',
  issue_date: '2026-08-01',
  due_date: '2026-08-31',
  sent_at: '2026-08-01T10:00:00Z',
  paid_at: null,
  created_at: '2026-08-01T10:00:00Z',
  notes_client: null,
  payment_conditions: null,
  aid_label: 'Aide MaPrimeRénov',
  aid_amount: 200,
  quote_id: 'quote-1',
  chantier_id: null,
  client_id: 'client-1',
  situation_number: 2,
  cumulative_pct: 65,
  period_from: '2026-07-01',
  period_to: '2026-07-31',
  retention_pct: 5,
  retention_amount: 134.1,
  market_reference: 'MARCHE-2026-018',
  is_reverse_charge: false,
  quote_number: 'DEV-2026-001',
  client: {
    id: 'client-1',
    company_name: 'Dupont Industrie',
    first_name: null,
    last_name: null,
    email: 'jean.dupont@dupont-industrie.fr',
    phone: '06 12 34 56 78',
    address_line1: '45 avenue de la République',
    postal_code: '69100',
    city: 'Villeurbanne',
    siret: '987 654 321 00098',
    siren: null,
    vat_number: 'FR98765432100',
    type: 'company',
  },
  items: [
    {
      id: 'inv-item-1',
      description: 'Fourniture',
      quantity: 1,
      unit: '__section__',
      unit_price: 0,
      unit_cost_ht: null,
      vat_rate: 20,
      position: 0,
      length_m: null,
      width_m: null,
      height_m: null,
      dim_quantity: 1,
      is_internal: false,
      material_id: null,
    },
    {
      id: 'inv-item-2',
      description: 'Garde-corps acier galvanisé',
      quantity: 12,
      unit: 'ml',
      unit_price: 145.5,
      unit_cost_ht: 90,
      vat_rate: 20,
      position: 1,
      length_m: 12,
      width_m: null,
      height_m: 1,
      dim_quantity: 1,
      is_internal: false,
      material_id: null,
    },
    {
      id: 'inv-item-3',
      description: 'Pose et installation',
      quantity: 2,
      unit: 'jour',
      unit_price: 380,
      unit_cost_ht: 250,
      vat_rate: 20,
      position: 2,
      length_m: null,
      width_m: null,
      height_m: null,
      dim_quantity: 1,
      is_internal: false,
      material_id: null,
    },
  ],
  payment_schedule: [],
}

async function main() {
  console.log('Chargement des polices depuis le filesystem...')
  const fontBytes = loadFontsFromDisk()

  console.log('Génération QuotePDF...')
  const quoteBuffer = await renderQuotePdfWithFonts({ quote, organization, client }, fontBytes)
  const quotePath = join(OUT_DIR, 'quote.pdf')
  writeFileSync(quotePath, quoteBuffer)
  console.log(`  -> ${quotePath} (${quoteBuffer.length} bytes)`)

  console.log('Génération InvoicePDF (situation de travaux)...')
  const invoiceBuffer = await renderInvoicePdfWithFonts({ invoice, organization }, fontBytes)
  const invoicePath = join(OUT_DIR, 'invoice.pdf')
  writeFileSync(invoicePath, invoiceBuffer)
  console.log(`  -> ${invoicePath} (${invoiceBuffer.length} bytes)`)

  console.log('\nTerminé. Ouvrir les PDF dans .scratch/pdf/ pour inspection visuelle.')
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
